### ISSUE TITLE
数据库插入Crash

### ISSUE THREAD

**Issue by jiayuanfa** [leavesCZY/Monitor#1]
![image](https://user-images.githubusercontent.com/9419485/101852679-2ca55580-3b99-11eb-8b4f-39ad7a22e152.png)

**Comment by leavesC** [comment]
可以先尝试使用这个版本来 catch 异常：'com.github.leavesC.Monitor:monitor:b43948260b'

**Comment by leavesCZY** [comment]
可以先尝试使用这个版本来 catch 异常：'com.github.leavesC.Monitor:monitor:b43948260b'。此外，能否提供下具体的接口返回值呢，我这样才好定位问题，是不是因为你加载了图片这类资源呢
