### ISSUE TITLE
编译报错，Kotlin版本问题

### ISSUE THREAD

**Issue by jarvan11** [leavesCZY/Monitor#4]
报错如下：
C:/Users/dell/.gradle/caches/modules-2/files-2.1/androidx.lifecycle/lifecycle-common/2.6.1/10f354fdb64868baecd67128560c5a0d6312c495/lifecycle-common-2.6.1.jar!/META-INF/lifecycle-common.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.8.0, expected version is 1.6.0.

**Comment by leavesCZY** [comment]
@jarvan11 这个可能就需要你升级下你项目中的 kotlin 版本才能解决了

**Comment by jarvan11** [comment]
> @jarvan11 这个可能就需要你升级下你项目中的 kotlin 版本才能解决了
升级会有其他问题，暂时不能升级，还有其他解决方法么

**Comment by jarvan11** [comment]
> @jarvan11 这个可能就需要你升级下你项目中的 kotlin 版本才能解决了

@leavesCZY 升级会有其他问题，暂时不能升级，还有其他解决方法么

**Comment by leavesCZY** [comment]
@jarvan11 你可以试下 Monitor 的 1.1.6 版本是否可用，这版本的 Kotlin 是 1.5.31

**Comment by jarvan11** [comment]
> @jarvan11 你可以试下 Monitor 的 1.1.6 版本是否可用，这版本的 Kotlin 是 1.5.31
@leavesCZY  Monitor 的 1.1.6 版本可以的

**Comment by leavesCZY** [comment]
@jarvan11 那看来的确和 Kotlin 版本有关。猜测是由于 lifecycle-common-2.6.1 是用 1.8.x 版本的 Kotlin 编译的，所以在低版本 Kotlin 上使用就会编译错误。你可以先使用 1.1.6 版本，后续等你更新了 Kotlin 再使用 Monitor 的最新版本
