### ISSUE TITLE
您好！请问一下如果okhttp的版本不一致，要如何做兼容呢？

### ISSUE THREAD

**Issue by qaz2531883** [leavesCZY/Monitor#5]
我的okHttp版本是3.14.9版本，而我看到框架里面okHttp的版本是4.11.0。而我使用debugApi的方式导入框架后，势必导致我原本的代码需要修改，这种情况下我是只能升级okhttp的版本吗？还是有别的办法？

**Comment by leavesCZY** [comment]
升级 OkHttp 是一种方案，3.x 版本的确是有点老了，Monitor 也没有哪个版本有用到 3.x 版本。另一种方案是可以去选用另一个类似的框架：https://github.com/ChuckerTeam/chucker，其 3.2.0 版本用到的 OkHttp 版本是 3.12.10，也可以符合你的需求
