### ISSUE TITLE
分享到QQ会卡死

### ISSUE THREAD

**Issue by SOCK-MAGIC** [leavesCZY/Monitor#6]
1.分享文本到Q群的时候会卡死，分享到电脑的时候会超出字数限制。
2.希望可以复制Url，cookie之类的文本可以长按复制

**Comment by leavesCZY** [comment]
1、会卡死是因为文本太长了吗？后续我看看是否要将文本转化为文件后再分享出去，这样也可以解决文本被截断的问题
2、这个我之前有考虑到，只是因为我发现 Jetpack compose 的文本长按复制功能有个会导致崩溃的 bug，所以就搁置了，后续我优化下，加上这个功能

**Comment by SOCK-MAGIC** [comment]
1.大文本发送会让qq卡死
2.查看大文本的时候希望能让json折叠和展开

**Comment by leavesCZY** [comment]
目前 v1.4.3 版本可以解决你的大部分问题了
