### ISSUE TITLE
看起来功能和 chucker 一样，有什么特殊的功能吗？

### ISSUE THREAD

**Issue by binglingziyu** [leavesCZY/Monitor#9]
https://github.com/ChuckerTeam/chucker

**Comment by leavesCZY** [comment]
我知道 chucker，说实话其实 chucker 的功能比 Monitor 要多一些，chucker 支持显示图片而 Monitor 目前不支持，Monitor 其实是我以前的一个实践项目而已：https://juejin.cn/post/6895740949025177607
